name: 'Install'
description: 'Sets up Node.js and runs install'

runs:
    using: composite
    steps:
        - name: Setup pnpm 8
          uses: pnpm/action-setup@v3
          with:
            version: 8
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
              node-version: 22
              registry-url: 'https://registry.npmjs.org'
              cache: 'npm'
        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
          env:
              PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
